[project]
name = "neural-emit-service"
authors = ["Blockchain Innovations Team"]
description = "A decentralized platform for event sentiment tracking and real-time feedback aggregation"
telemetry = false
requirements = []
[contracts.neural-event-hub]
path = "contracts/neural-event-hub.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
